FROM node:20.15.0 AS build

WORKDIR /app

COPY ./service-a-expressjs/package.json ./
COPY service-a-expressjs/yarn.lock ./

RUN yarn install

COPY ./service-a-expressjs/ ./

FROM node:20.15.0-alpine3.20

WORKDIR /

COPY --from=build /app ./

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]
