FROM golang:1.23 AS build

WORKDIR /app

COPY ./service-b-go/go.mod ./
COPY ./service-b-go/go.sum ./

RUN go mod download

COPY ./service-b-go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /service-b ./cmd/server

RUN chmod a+x /service-b

FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /service-b /service-b

EXPOSE 8080

CMD ["./service-b"]
