name: "Building and Publishing Docker"
description: "Builds and publishes a Docker image to Github packages"
inputs:
  registry:
    description: "Registry to push to, it's always Github packages"
    default: ghcr.io
  image_name:
    description: "The name of the image to use"
    required: true
  token:
    description: "Token to use when publishing the image"
    required: true
  file:
    description: "Path to the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        file: ${{ inputs.file }}
        tags: |
          ${{ inputs.registry }}/${{github.repository}}/${{inputs.image_name}}:latest
