name: Lint OpenAPI Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/docs/openapi/**.yaml'
      - '**/docs/openapi/**.yml'

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

concurrency:
  group: ci-lint-openapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changed-directories:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      CHANGED_DIRS: ${{ steps.changed-directories.outputs.all_modified_files }}
      CHANGED_DIRS_COUNT: ${{ steps.changed-directories.outputs.all_modified_files_count }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check changed OpenAPI directories
        id: changed-directories
        uses: tj-actions/changed-files@v44.5.2
        with:
          dir_names: true
          files: '**/docs/openapi/**.{yaml,yml}'
          dir_names_exclude_current_dir: true

  lint-openapi:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs: check-changed-directories
    steps:
      - name: Check out repository code
        env:
          CHANGED_DIRS_COUNT: ${{ needs.check-changed-directories.outputs.CHANGED_DIRS_COUNT }}
        if: ${{ fromJSON(env.CHANGED_DIRS_COUNT) > 0 }}
        uses: actions/checkout@v4

      - name: Prepare paths for linting
        id: prepare-paths
        env:
          PATHS: ""
        run: |
          for dir in ${{ needs.check-changed-directories.outputs.CHANGED_DIRS }}; do
            echo "PATHS=$PATHS$dir/openapi.yaml" >> "$GITHUB_OUTPUT"
          done

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-linting-openapi-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-linting-openapi-
            ${{ runner.os }}-

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Run Redocly Linting
        uses: ./.github/actions/lint-openapi-action
        with:
          paths: ${{ steps.prepare-paths.outputs.PATHS }}
