name: Lint & Test Golang Code

on:
  pull_request:
    branches:
      - main
    paths:
      - '*-go/**.go'
      - '*-go/go.mod'
      - '*-go/go.sum'

concurrency:
  group: ci-lint-golang-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changed-directories:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      CHANGED_DIRS: ${{ steps.set-changed-directories.outputs.changed_dirs }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check changed Golang directories
        id: changed-directories
        uses: tj-actions/changed-files@v44.5.2
        with:
          dir_names: true
          dir_names_max_depth: 1
          files: |
            *-go/**.go
            *-go/go.mod
            *-go/go.sum
          dir_names_exclude_current_dir: true

      - name: Set Changed Directories
        id: set-changed-directories
        env:
          CHANGED_DIRS_COUNT: ${{ steps.changed-directories.outputs.all_changed_files_count }}
        if: ${{ fromJSON(env.CHANGED_DIRS_COUNT) > 0 }}
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-directories.outputs.all_changed_files }} | jq -Rrjc 'split(" ")' | jq -r 'tostring')
          echo "changed_dirs=$DATA" >> "$GITHUB_OUTPUT"

  lint-and-tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs: check-changed-directories
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.check-changed-directories.outputs.CHANGED_DIRS) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache-dependency-path:  "${{ matrix.dir }}/*.sum"

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: go get ./...

      - name: Run Go mod tidy
        working-directory: ${{ matrix.dir }}
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          working-directory: ${{ matrix.dir }}
          args: --out-format=github-actions

      - name: Test with the Go CLI
        working-directory: ${{ matrix.dir }}
        run: mkdir -p .coverage && go test ./... -race -coverprofile=./.coverage/coverage.out -covermode=atomic -coverpkg=./...

      - name: Generate Test Coverage
        working-directory: ${{ matrix.dir }}
        run: go tool cover -func=./.coverage/coverage.out
